// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission6_nsweiler.Models;

namespace Mission6_nsweiler.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20230213213849_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission6_nsweiler.Models.MovieResponse", b =>
                {
                    b.Property<int>("movieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("lentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("year")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("movieId");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            movieId = 1,
                            category = "Action",
                            director = "",
                            edited = false,
                            lentTo = "Styles Weiler",
                            notes = "",
                            rating = "PG-13",
                            title = "Avengers",
                            year = "2012"
                        },
                        new
                        {
                            movieId = 2,
                            category = "Action",
                            director = "George Lucas",
                            edited = false,
                            lentTo = "Styles Weiler",
                            notes = "",
                            rating = "PG-13",
                            title = "Star Wars",
                            year = "1977"
                        },
                        new
                        {
                            movieId = 3,
                            category = "Action",
                            director = "Rocky",
                            edited = false,
                            lentTo = "Styles Weiler",
                            notes = "",
                            rating = "PG",
                            title = "Rocky",
                            year = "1977"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
